---
image:
  pullSecret:
    enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: http01
  path: /
  hosts:
    - api.shelterme.com.au
  tls:
   - secretName: api-shelterme-com-au-tls
     hosts:
       - api.shelterme.com.au
