# Default values for fastify-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
replicaCount: 3

version: v1

image:
  repository: r.fala.cl/tottus/orion/fastify-demo
  tag: latest
  pullPolicy: Always
  pullSecret:
    enabled: false
    name: docker-reg
    registry: https://hub.docker.com
    username: username
    password: password
  annotations:
    prometheus.io/scrape: "true"

container:
  host: 0.0.0.0

service:
  type: NodePort
  port: 4444
  annotations: {}

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - example.com
  tls: []
  # - secretName: example-com-tls
  #   hosts:
  #     - examples.com

resources:
  limits:
    cpu: 500m
    memory: 250Mi
  requests:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 10
  targetAverageUtilization: 75

nodeSelector: {}

tolerations: []

affinity: {}
